### ISSUE TITLE
Code uses GPL license and LICENSE.md says MIT license

### ISSUE THREAD

**Issue by Ed-k** [sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library#1]
The LICENSE.md file says that this library is under the MIT license but the source files say it is GPL ([in the files in /src](https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library/blob/73830352cb5271d14ce68abc3bf0fa7ab8baba80/src/SparkFun_MMC5983MA_Arduino_Library.cpp#L14
)). Which license should this be using?

**Comment by nseidle** [comment]
Sorry for the confusion. It should be MIT. I'll try to get the cpp files updated shortly.
