### ISSUE TITLE
Library 1.10 data does not comply with the data of 1.0.3 library

### ISSUE THREAD

**Issue by fred9999** [sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library#12]
Hi again,

The magnetometer data acquired with the library ver. 1.10 does not comply with the data of 1.0.3 library at all, making all previously working scripts useless.

Please find hereby a data set taken by running the Example1-I2C_Simple_measurement.ino with both library versions, magnetometer being in exactly the same position

library ver. 1.0.3
X axis raw value: 122785	Y axis raw value: 130141	Z axis raw value: 135378
X axis field (Gauss): -0.50580	Y axis field (Gauss): -0.05682	Z axis field (Gauss): 0.26282

library ver. 1.10
X axis raw value: 139837	Y axis raw value: 132878	Z axis raw value: 125884
X axis field (Gauss): 0.53497	Y axis field (Gauss): 0.11023	Z axis field (Gauss): -0.31665

Hopefully you can fix this issue. Thank you.

Kind regards,
Fred

**Comment by PaulZC** [comment]
Hello Fred (@fred9999 ),

Unfortunately, this is expected.

In version 1.0.3 of the library, the Auto-Set-Reset was being repeatedly enabled. This is what was causing the spikes in the data.

In version 1.1.0 I have corrected this. But it means the the readings will be different as the sensor is not being set and reset periodically.

If you wish to make v1.1.0 the same as 1.0.3, please add these two lines to your ```setup``` code _after_ the ```myMag.softReset()```:

```
myMag.enableAutomaticSetReset();
myMag.setFilterBandwidth(200);
```

I _think_ the data is then the same as v1.0.3 - but without the spikes. It is difficult to tell... Please test it and let me know if it corrects your issue.

I will be adding a new example, which shows how to perform a manual set-reset and calculate the sensor offset. It might help you going forward?

Best wishes,
Paul

**Comment by PaulZC** [comment]
Please see v1.1.1 for the [new example](https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library/blob/main/examples/Example7-I2C_Sensor_Offset/Example7-I2C_Sensor_Offset.ino)

**Comment by fred9999** [comment]
Hi Paul,

Brilliant! 

Thank you Paul for the ultra quick reply. Your solution worked like a charm and I got my old scripts working again.

The new set/reset feature you introduced sounds like really useful one. I will definitely look into it closer. The chip's temperature can fluctuate outdoors 20-30C easily throughout a day at summer time. Even more if the device containing the magnetometer is under the direct sunlight. That would be really great if that feature would help to eliminate the inaccuracy of the magnetometer caused by the temperature fluctuations.

Thanks again, you’re doing a great job,

Fred

**Comment by PaulZC** [comment]
Hi Fred,

Thanks for the update. Glad that's working for you. I am going to pin this issue - to make it easier for other users to find.

Closing...

Best wishes,
Paul
