### ISSUE TITLE
Channel X readout is almost constant

### ISSUE THREAD

**Issue by pjalocha** [sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library#14]
I am trying to read the magnetometer with the library and it all reads alright except for the channel X which is only like noisy but gives no changes when the orientation changes. I read about similar problems elsewhere but there is no specific solution. Is there a trick to make it going ? I tried to enable it explicitely but this does hot help.

Here is a mention of a similar problem and the solution was a new code but the code is not given there.
https://electronics.stackexchange.com/questions/617016/magnetometer-mmc5983ma-x-axis-only-works-once

**Comment by pjalocha** [comment]
Thank you,

I interface with I2C, library is 1.1.1, I read all three with a single call like you suggest.
I will try your other suggestions.

Pawel.

**Comment by PaulZC** [comment]
Hi Pawel (@pjalocha ),

I am going to close this issue. Please reopen it if you need more help.

Best wishes,
Paul

**Comment by nbelakovski** [comment]
I experienced this same issue as well, and the extra example code linked above (which now appears to be in this repo as example 7) fixed it for me. Oddly the fix persisted even after switching back to a different program, i.e. I didn't have to store the offsets calculated by that program. Also oddly, I was calling `enablePeriodicSet` along with `setPeriodicSetSamples` at several points during my debugging, which I think should have executed the same routines on the chip as the manual set/reset performed in example 7, and yet it was only by performing them manually with that program that the chip actually started working as expected.

Thanks for the assistance.
