### ISSUE TITLE
Inverted arguments in call to atan2 in examples

### ISSUE THREAD

**Issue by JosefWN** [sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library#19]
Aren't the arguments inverted for calls to `atan2` in the examples? `atan2(y, x)` I believe is the signature?

https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library/blob/8b22bc4e68e6f2331d419b0571dd93adc7a36f2f/examples/Example2-I2C_Digital_compass/Example2-I2C_Digital_compass.ino#L74

I would have thought it should look something like this (without inversion of the y-axis)?
```c
 heading = atan2(scaledY, scaledX); 
```

EDIT: The reason for the inverted arguments being that `atan2(y, x)` maintains the ordering of `x` and `y` in the corresponding `atan(y/x)`, so `y, x` reads _y over x_.

**Comment by PaulZC** [comment]
Hi @JosefWN ,

What do you see when you run the example? IIRC, the heading is correct for me in the UK. We want the heading to be zero when the Y axis is pointing North, ascending clockwise. Without correction, atan2 is zero when oriented East along the X axis, ascending counter clockwise.

Best wishes,
Paul

**Comment by JosefWN** [comment]
Ah, sorry, I was too quick on the trigger, a bit tired. Yes, inverted arguments and also inverted axes to measure against brings us back to `(x, y)` 😅 The whole expression threw me off a bit as I was skimming through the code, the board should arrive tomorrow!

Interesting to see the y-axis inverted nonetheless. I will try it out and let you know!

**Comment by PaulZC** [comment]
Thanks @JosefWN,

Please close this when you have your board and have tested the example.

Enjoy!
Paul

**Comment by JosefWN** [comment]
Seems correct!
