### ISSUE TITLE
SparkFun_MMC5983MA_Arduino_Library.cpp - get* - delay(1) --> micros();

### ISSUE THREAD

**Issue by mvschaefer** [sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library#20]
ln259 - getTemperature()
ln947 - getMeasurementX()
ln986 - getMeasurementY()
ln1025 - getMeasurementZ()
ln1064 - getMeasurementXYZ()

can all benefit from calling micros() (or anything < a full 1msec delay - crikey folks!..) instead of delay(1)...

**Comment by PaulZC** [comment]
Hi Mike (@mvschaefer ),

Using ```micros()``` would be a breaking change. It is only supported on newer platforms.

If you need to sample at the full 1kHz, use interrupts. It's the most efficient way of reading the sensor. See [Example6](https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library/blob/main/examples/Example6-SPI_Fast_Continuous_measurement/Example6-SPI_Fast_Continuous_measurement.ino) for details.

Best wishes,
Paul
