### ISSUE TITLE
Digital Compass - advice for beginner please

### ISSUE THREAD

**Issue by chelliwell** [sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library#21]
Got my Qwiic board literally today. I've ported the I2C to my MCU, and pulled in the code from the Digital Compass example.
The heading result isn't coming out well though:  turning the board horizontally thru ~90 degree steps I'm getting approx. 75, 115, 155, 205. (No metal within 30cm or more).
Obviously I'm not familiar yet with the device or library, but is there anything obvious I'm missing? Incorrect scaling on the X/Y? I noticed the Issue re. the bridge offset - haven't figured out if this is something needed....
On the plus side, my application doesn't need accuracy better than about 5 degrees, but I'm way off at present.
Any Dummy get-it-going-well-enough advice welcome! Thanks.

**Comment by PaulZC** [comment]
Hi @chelliwell ,

Welcome!

The magnetometer needs calibration (gain and offset) before it will give you an accurate heading. The code example is really only intended to get your started. There are comments in the code about where to start with calibration. Calibration has also been discussed many times on our Forum:

https://community.sparkfun.com/search?q=mmc5983%20calibration%20order%3Alatest

I hope this helps,
Paul
